apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["cpu"]'
    opendatahub.io/template-display-name: vLLM CPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-xeon-runtime
    openshift.io/display-name: llama32-3b-cpu
  name: llama32-3b-cpu
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - llama3_json
        - '--chat-template'
        - /app/data/template/tool_chat_template_llama3.2_json.jinja
        - '--max-model-len'
        - '2048'
        - '--dtype'
        - 'bfloat16'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm:vllm-cpu-v2-25-on-push-h8xq2-build-s390x-image'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /app/data/template/tool_chat_template_llama3.2_json.jinja
          name: chat-template-volume
          subPath: tool_chat_template_llama3.2_json.jinja
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 4Gi
      name: shm
    - name: chat-template-volume
      configMap:
        name: chat-template
