apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${PROJECT}

resources:
  - oci-data-connection.yaml
  - chat-template-configmap.yaml
  - servingruntime.yaml
  - inferenceservice.yaml
