apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["habana.ai/gaudi"]'
    opendatahub.io/template-display-name: vLLM Intel Gaudi Accelerator ServingRuntime for KServe
    opendatahub.io/accelerator-name: gaudi-hpu-profile
    opendatahub.io/template-name: vllm-gaudi-runtime
    openshift.io/display-name: granite32-8b-hpu
  name: granite32-8b-hpu
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=granite'
        - '--chat-template=/app/data/template/tool_chat_template_granite.jinja'
        - '--block-size=128'
        - '--dtype=bfloat16'
        - '--max-model-len=33024'
        - '--gpu-memory-util=0.99'
        - '--max-num-seqs=160'
        - '--max-num-prefill-seqs=16'
        - '--num-scheduler-steps=1'
        - '--use-padding-aware-scheduling'
        - '--tensor-parallel-size=1'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: "/tmp/hf_home"
      image: 'quay.io/modh/vllm:vllm-gaudi-v2-25-on-push-n7985-build-images'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
